---
version: '1'
services:
    dev:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        volumes:
            - './app:/var/www/html'

    prod:
        image: nginx:latest
        ports:
            - '8888:8080'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
        depends_on:
            - dev