---
version: '1'
services:
    dev:
        build:
            context: .
        volumes:
            - './war:/opt/apache-tomcat-9.0.34/webapps'

    prod:
        image: tomcat:9.0
        ports:
            - '8888:8080'
        volumes:
            - './war/hello-1.0:/usr/local/tomcat/webapps/hello-1.0'
        depends_on:
            - dev